name: Django CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      CI: 'true'
      SECRET_KEY: 'ci-test-key-not-for-production'  # You can hardcode this for CI
      DEBUG: 'False'
      ALLOWED_HOSTS: 'localhost,127.0.0.1'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Postgres
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for Postgres..."
          sleep 1
        done

    - name: Setup database
      working-directory: backend
      run: |
        python manage.py migrate --run-syncdb

    - name: Run tests
      working-directory: backend
      run: |
        python manage.py test --keepdb --verbosity=2